name: boost2html
discription: THIS IS GENERATE BY boost2html FROM boostnote's' SNIPPETS
autor: lazyboy
basePath: /codes
snippetTitle: Snippets
BoostStorage: X:/code/
email: xbotao2014@gmail.com
website: http://www.lazyboy.site
sitename: lazyboy.site
since: 2017